config/routes.rb
Rails.application.routes.draw do

  resources :users, only: %i[ index new create show ]
  resource :session
  resources :posts, only: %i[ index new create show ]

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  # normalizes :email, with: ->(email) {email.strip.downcase} RAILS 7.1 ONLY
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to do that." unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create ]
  def index
    @posts = Post.all.order(created_at: :asc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # if user = User.authenticate_by(params.require(:user).permit(:email, :password)) // por que nao funcionou?
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      login user
      redirect_to root_path, notice: "You have been logged in"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]
  def index
    @users = User.all.order(created_at: :asc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    @user.email.downcase!
    if @user.save
      login @user
      redirect_to root_path, notice: "You have been signed in"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container mx-auto">
    <%# <div class="bg-white"> %>
      <header class="w-9/12 mx-auto flex items-center justify-between flex-wrap bg-indigo-950 rounded-lg p-6 mt-3">
        <div class="flex items-center flex-shrink-0 text-white mr-6">
          <%= link_to "Blog", root_path, class: "font-semibold text-xl text-white tracking-tight no-underline" %>
        </div>
        <%# <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-blue-100 border-teal-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div> %>
        <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
          <div class="text-sm lg:flex-grow text-center">
            <%# <%= link_to "Homepage", root_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-100 hover:text-white mr-4" %>
            <%= link_to "Posts", posts_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-100 hover:text-white mr-4" %>
            <%= link_to "Users", users_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-100 hover:text-white mr-4" %>
          </div>
          <% if user_signed_in? %>
            <div>
                <%= button_to "Log out", session_path, method: :delete, class: "text-white bg-gradient-to-r from-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-4 py-2 text-center leading-none" %>
            </div>
          <% else %>
            <div>
                <%= link_to "Sign up", new_user_path, class: "inline-block text-sm px-4 py-2 leading-none rounded text-white mt-4 lg:mt-0" %>
                <%= link_to "Log in", new_session_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-950 hover:bg-white mt-4 lg:mt-0" %>
            </div>
          <% end %>
        <%# </div> %>
      </header>
    </div>

    <main class="bg-white container mx-auto prose mt-2">
      <div><%= notice %></div>
      <div><%= alert %></div>

      <%= yield %>
    </main>
  </body>
</html>

app/views/main/index.html.erb
<main class="container mx-auto prose">
  <h1 class="text-center">Home</h1>
  <% if user_signed_in? %>
    <%= link_to "Create New Post", new_post_path %>
  <% end %>
</main>

app/views/posts/index.html.erb
<main class="container mx-auto prose pt-5">
  <h1 class="text-center">Posts</h1>
  <div class="mb-5">
    <% if user_signed_in? %>
      <button class="text-white bg-gradient-to-r from-purple-700 via-indigo-600 to-indigo-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-purple-300 dark:focus:ring-purple-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">
        <%= link_to "Create New Post", new_post_path, class: "no-underline text-white font-semibold" %>
      </button>
    <% end %>
  </div>

  <% @posts.each do |post| %>
    <div id="post-card" class="bg-gray-50 p-3 mt-3 rounded-lg">
      <div class="flex items-center gap-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M12 4a4 4 0 0 1 4 4a4 4 0 0 1-4 4a4 4 0 0 1-4-4a4 4 0 0 1 4-4m0 10c4.42 0 8 1.79 8 4v2H4v-2c0-2.21 3.58-4 8-4"/></svg>
        <span><%= post.user.name %> • <span class="text-gray-400">9h</span></span>
      </div>

      <div>
        <p>
          <%= link_to post_path(post), class: "no-underline text-xl" do %>
            <%= post.title %>
          <% end %>
        </p>
        <p class="text-sm truncate"><%= post.body %></p>
        <nav class="flex gap-2">
          <span class="flex bg-gray-200 rounded-full gap-1 p-2 items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none"><path d="M24 0v24H0V0zM12.593 23.258l-.011.002l-.071.035l-.02.004l-.014-.004l-.071-.035q-.016-.005-.024.005l-.004.01l-.017.428l.005.02l.01.013l.104.074l.015.004l.012-.004l.104-.074l.012-.016l.004-.017l-.017-.427q-.004-.016-.017-.018m.265-.113l-.013.002l-.185.093l-.01.01l-.003.011l.018.43l.005.012l.008.007l.201.093q.019.005.029-.008l.004-.014l-.034-.614q-.005-.019-.02-.022m-.715.002a.02.02 0 0 0-.027.006l-.006.014l-.034.614q.001.018.017.024l.015-.002l.201-.093l.01-.008l.004-.011l.017-.43l-.003-.012l-.01-.01z"/><path fill="currentColor" d="M13.06 3.283a1.5 1.5 0 0 0-2.12 0L5.281 8.939a1.5 1.5 0 0 0 2.122 2.122L10.5 7.965V19.5a1.5 1.5 0 0 0 3 0V7.965l3.096 3.096a1.5 1.5 0 1 0 2.122-2.122z"/></g></svg>
            <span class="text-xs font-bold">20</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none"><path d="M24 0v24H0V0zM12.593 23.258l-.011.002l-.071.035l-.02.004l-.014-.004l-.071-.035q-.016-.005-.024.005l-.004.01l-.017.428l.005.02l.01.013l.104.074l.015.004l.012-.004l.104-.074l.012-.016l.004-.017l-.017-.427q-.004-.016-.017-.018m.265-.113l-.013.002l-.185.093l-.01.01l-.003.011l.018.43l.005.012l.008.007l.201.093q.019.005.029-.008l.004-.014l-.034-.614q-.005-.019-.02-.022m-.715.002a.02.02 0 0 0-.027.006l-.006.014l-.034.614q.001.018.017.024l.015-.002l.201-.093l.01-.008l.004-.011l.017-.43l-.003-.012l-.01-.01z"/><path fill="currentColor" d="M10.5 16.035L7.404 12.94a1.5 1.5 0 1 0-2.122 2.121l5.657 5.657a1.5 1.5 0 0 0 2.122 0l5.657-5.656a1.5 1.5 0 1 0-2.122-2.122L13.5 16.035V4.5a1.5 1.5 0 0 0-3 0z"/></g></svg>
          </span>
          <span class="flex bg-gray-200 rounded-full gap-1 p-2 items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M12 2C6.477 2 2 6.477 2 12a10 10 0 0 0 .951 4.262l-.93 4.537a1 1 0 0 0 1.18 1.18l4.537-.93c1.294.61 2.74.95 4.262.95c5.523 0 10-4.476 10-10c0-5.522-4.477-10-10-10" clip-rule="evenodd"/></svg>
            <span class="text-xs font-bold">4</span>
          </span>
          <span class="flex bg-gray-200 rounded-full gap-1 p-2 items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M11.293 2.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1-1.414 1.414L13 5.414V15a1 1 0 1 1-2 0V5.414L9.707 6.707a1 1 0 0 1-1.414-1.414zM4 11a2 2 0 0 1 2-2h2a1 1 0 0 1 0 2H6v9h12v-9h-2a1 1 0 1 1 0-2h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z"/></svg>
            <span class="text-xs font-bold">Share</span>
          </span>
        </nav>
      </div>
    </div>
  <% end %>
</main>

app/views/posts/new.html.erb
<main class="container mx-auto prose mt-5">
  <h1 class="text-2xl font-bold mb-4">Create a Post</h1>

  <%= form_with model: @post, class: "max-w-md" do |f| %>
    <% if f.object.errors.any? %>
      <% f.object.errors.full_messages.each do |message| %>
        <div class="text-red-500 mb-2"><%= message %></div>
      <% end %>
    <% end %>

    <div class="mb-4">
      <%= f.label :title, class: "block font-bold mb-2" %>
      <%= f.text_field :title, class: "w-full border border-gray-300 rounded py-2 px-3" %>
    </div>

    <div class="mb-4">
      <%= f.label :body, class: "block font-bold mb-2" %>
      <%= f.text_area :body, class: "w-full border border-gray-300 rounded py-2 px-3" %>
    </div>

    <div>
      <%= f.submit "Create", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</main>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.body %></p>

<p>Posted by: <%= @post.user.name %></p>

<p>Posted on: <%= @post.created_at %></p>

app/views/users/index.html.erb
<main class="container mx-auto prose pt-5">
  <h1 class="text-center">Users</h1>
  <% if user_signed_in? %>
    <% @users.each do |user| %>
      <div id="user-card" class="grid bg-gray-50 p-3 mt-3 rounded-lg justify-center text-center">
        <div class="grid gap-2 justify-items-center">
          <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" alt="profile photo" class="w-36 h-36 rounded-full object-cover">
          <%= link_to user_path(user), class: "no-underline text-xl font-bold" do %>
            <span class="text-center"><%= user.name %></span>
          <% end %>
          <span class="text-center"><%= user.email %></span>
          <span class="text-center">Posts: <%= user.posts.count %></span>
          <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Follow</button>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="text-center mt-5">
      <p class="text-lg">You need to be logged in to view this content.</p>
      <%= link_to "Log in", new_session_path, class: "no-underline bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded" %>
    </div>
  <% end %>
</main>

app/views/users/new.html.erb
<main>
	<h1 class="text-2xl font-bold mb-4">Sign Up</h1>

	<%= form_with model: @user do |f| %>
		<% if f.object.errors.any? %>
			<% f.object.errors.full_messages.each do |message| %>
				<div class="text-red-500 mb-2"><%= message %></div>
			<% end %>
		<% end %>

		<div class="mb-4">
			<%= f.label :name, class: "block font-medium mb-1" %>
			<%= f.text_field :name, autofocus: true, class: "w-full border border-gray-300 rounded px-3 py-2" %>
		</div>

		<div class="mb-4">
			<%= f.label :email, class: "block font-medium mb-1" %>
			<%= f.email_field :email, class: "w-full border border-gray-300 rounded px-3 py-2" %>
		</div>

		<div class="mb-4">
			<%= f.label :password, class: "block font-medium mb-1" %>
			<%= f.password_field :password, class: "w-full border border-gray-300 rounded px-3 py-2" %>
		</div>

		<div class="mb-4">
			<%= f.label :password_confirmation, class: "block font-medium mb-1" %>
			<%= f.password_field :password_confirmation, class: "w-full border border-gray-300 rounded px-3 py-2" %>
		</div>

		<div>
			<%= f.submit "Sign Up", class: "bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded" %>
		</div>
	<% end %>
</main>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<div>
  <%= @user.email %>
</div>

<%= link_to "Home", root_path %>